# L3LS Fabric Values - update these values with caution,
# SOME CHANGES COULD BE DISRUPTIVE.

fabric_name: {{ cookiecutter.general.fabric_name }}

underlay_routing_protocol: BGP

# Point to Point Network Summary range, assigned as /31 for each
# uplink interfaces
# Assign range larger then total [Spines * total potential leafs * 2]
underlay_p2p_network_summary: {{ cookiecutter.general.underlay_p2p_network_summary }}

# IP address range for evpn loopback for all switches in fabric,
# assigned as /32s
# Assign range larger then total Spines + total leafs switches
overlay_loopback_network_summary: {{ cookiecutter.general.overlay_loopback_network_summary }}

# VTEP VXLAN Tunnel source loopback IP for leaf switches, assigned in /32s
# Assign range larger then total leaf switches
vtep_loopback_network_summary: {{ cookiecutter.general.vtep_loopback_network_summary }}

# Enable vlan aware bundles
vxlan_vlan_aware_bundles: {{ vxlan_vlan_aware_bundles }}

# bgp peer groups passwords
bgp_peer_groups:
  IPv4_UNDERLAY_PEERS:
    password: {{ cookiecutter.general.bgp_peering_password }}
  EVPN_OVERLAY_PEERS:
    password: {{ cookiecutter.general.bgp_peering_password }}

# Spine Switches
spine:
  bgp_as: {{ cookiecutter.general.spine_bgp_asn }}
  # defines the range of acceptable remote ASNs from leaf switches
  leaf_as_range: {{ cookiecutter.general.leaf_as_range }}
  nodes:
{%- for spine in cookiecutter.fabric.spine_list %}
    {{ spine.hostname }}:
      id: {{ spine.id }}
      mgmt_ip: {{ spine.management_ip }}
      platform: {{ spine.platform }}
{%- endfor %}

# Leaf switch groups
# A maximum of two nodes can form a leaf group
# When two nodes are in a leaf group this will automatically form mlag pair

l3leaf:
  defaults:
    # virtual router mac for VNIs assigned to Leaf switches
    # format: xx:xx:xx:xx:xx:xx
    virtual_router_mac_address: {{ cookiecutter.general.virtual_router_mac_address }}
    spanning_tree_priority: {{ cookiecutter.general.l3leaf_stp_priority }}
    spanning_tree_mode: {{ cookiecutter.general.l3leaf_stp_mode }}
  node_groups:
{%- for pod in cookiecutter.fabric.pod_list %}
    {{ pod.name }}:
      bgp_as: {{ pod.asn }}
      nodes:
{%-     for leaf in pod.leafs %}
        {{ leaf.hostname }}:
          id: {{ leaf.id }}
          mgmt_ip: {{ leaf.management_ip }}
          platform: {{ leaf.platform }}
          spines: {{ leaf.spines }}
          uplink_to_spine_interfaces: {{ leaf.uplink_to_spine_interfaces }}
          spine_interfaces: {{ leaf.spine_interfaces }}
{%-     endfor %}
{%- endfor %}

p2p_uplinks_mtu: {{ cookiecutter.general.underlay_p2p_link_mtu }}
